### ISSUE TITLE
More like commentary than an issue

### ISSUE THREAD

**Issue by JeffVeit** [andrea-alfonsi/nyx#1]
Seeing as I have been looking at Rust plugin systems today, and I found your work amongst other things, I thought you might also be interested in the other related efforts if you haven't found them yourself:

- https://nullderef.com/series/rust-plugins/ - someone investigating all the ways
- https://michael-f-bryan.github.io/rust-ffi-guide/dynamic_loading.html
- https://adventures.michaelfbryan.com/posts/plugins-in-rust/
- https://willcrichton.net/rust-api-type-patterns/registries.html - focus on type safety
- https://github.com/dtolnay/inventory - a registry crate using ctor - there are also some forum discussions about this approach which I haven't included here. This is pretty interesting in that it's almost annotation to create a registry of a type.
- https://github.com/dtolnay/linkme
- https://github.com/VPlugin - looks to me like it assumes that it will load a plugin at runtime. I think having compiled and loadable plugins is more useful.
- https://zicklag.github.io/rust-tutorials/rust-plugins.html - mileage varies

These are the general issues I've thought of:

* The ability to have different registries - e.g. one for flags and another for drawing objects to the screen, even if they have the same type.
* Ability to register items without assuming they need loading - so items included at compile time. 
* Safety - including possible initialisation and teardown
* The ability to pass large amounts of data - e.g. a registry in a game may be involved in pipelining the screen.
* I like the idea of being able include in a registry through annotation, but it must also be possible to include search and include at runtime
* All the platforms. Some projects do not work everywhere.

**Comment by JeffVeit** [comment]
And since it's not so much an issue, I'm immediately closing it.

**Comment by squidward-q-byte** [comment]
Thank you very much for your comment. The project is currently in the alpha phase, so there will definitely be many changes. I really appreciate these suggestions and I will try to check all the links as soon as possible.
If you have any other suggestions or opinions, please feel free to comment.

**Comment by JeffVeit** [comment]
Something I forgot - when I was looking for a plugin crate, one of the searches I did was https://crates.io/search?page=1&q=plugins ... this should be interesting for you because it shows a bunch of use-cases - systems that are using plugins, usually with their own local plugin mechanism. A good plugin system should be able to replace all(?) of these with a general mechanism.

Good luck!
